## 03-Feature Engineering

The objective of this step is to create more meaningful variables from the cleaned dataset. `../data/processed/customer_cleaned.csv`

These new features will improve both the exploratory analysis and customer segmentation process.

In [1]:
import pandas as pd
from src.feature_engineering import create_features

### 1. Load cleaned data
The cleaned dataset is loaded with `Dt_Customer` parsed as datetime directly on read,
so no conversion is needed later.

In [2]:
# load data
cleaned_data = pd.read_csv("../data/processed/customer_cleaned.csv",parse_dates=['Dt_Customer'])
cleaned_data.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,5,0,0,0,0,0,0,3,11,0

### 2. Feature engineering

The `create_features()` function builds the following derived columns :

| Feature | Description |
|---|---|
| `Age` | Customer age derived from `Year_Birth` |
| `Total_Children` | Sum of `Kidhome` and `Teenhome` |
| `Total_Spending` | Total spend across all product categories |
| `Customer_since` | Number of days since enrollment |
| `accepted_campaigns` | 1 if the customer responded to at least one campaign |
| `Age_Group` | Age bracket (18-29, 30-39, ..., 70+) |

In [3]:
cleaned_data = create_features(cleaned_data)

Preview the changes

In [4]:
cleaned_data.head(5)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,Complain,Z_CostContact,Z_Revenue,Response,Age,Total_Children,Total_Spending,Customer_since,accepted_campaigns,Age_Group
0,5524,1957,Graduation,Single,58138.0,0,0,2012-09-04,58,635,...,0,3,11,1,69,0,1617,5046,1,60-69
1,2174,1954,Graduation,Single,46344.0,1,1,2014-03-08,38,11,...,0,3,11,0,72,2,27,4496,0,70+
2,4141,1965,Graduation,Together,71613.0,0,0,2013-08-21,26,426,...,0,3,11,0,61,0,776,4695,0,60-69
3,6182,1984,Graduation,Together,26646.0,1,0,2014-02-10,26,11,...,0,3,11,0,42,1,53,4522,0,40-49
4,5324,1981,PhD,Married,58293.0,1,0,2014-01-19,94,173,...,0,3,11,0,45,1,422,4544,0,40-49

### 3. Export

The enriched dataset is exported to `data/processed/` for use in the next step.

In [5]:
cleaned_data.to_csv('../data/processed/customer_features.csv', index=False)